[GlobalSettings]

# CmprAlgo = ALGO_INTERP_LORENZO
#CmprAlgo = ALGO_INTERP
CmprAlgo = ALGO_LORENZO_REG

[AlgoSettings]

# settings for interpolation algorithm
# INTERP_ALGO_LINEAR
#      use linear interpolation
# INTERP_ALGO_CUBIC
#      use cubic spline interpolation
InterpolationAlgo = INTERP_ALGO_CUBIC
InterpolationDirection = 0

#settings for lorenzo and regression algorithms
Lorenzo = Yes
Lorenzo2ndOrder = No
Regression = No
Regression2ndOrder = No
#BlockSize = 6